### ISSUE TITLE
Use enums

### ISSUE THREAD

**Issue by bluciam** [plaice/Zebrackets#14]
There is a lot of ugly code which needs refactoring. We will use https://docs.python.org/3.4/library/enum.html.
But first the algorithm in zebraFilter needs to be worked out.

**Comment by bluciam** [comment]
Working on zebraFilter and it is probably done.

**Comment by plaice** [comment]
The code was partially rewritten using enums, and tested with python 3.4.3. Unfortunately, there is a bug in the implementation, and a variable assigned an enumerated value could not be used as the argument to a dictionary lookup. The changes were left in branch EnumBug.
