### ISSUE TITLE
Testing infrastructure for zebraFont.py: input arguments

### ISSUE THREAD

**Issue by plaice** [plaice/Zebrackets#7]
1.  Add flag to input arguments to just test validity of these arguments. (✅)
- Create unit tests for testing all of the argument-checking infrastructure.
- Check that input arguments are mutually consistent.

**Comment by plaice** [comment]
- The --checkargs flag is added to interface (1).
- The Computer Modern fonts are added (4).

**Comment by plaice** [comment]
- Valid Computer Modern font families are enumerated, and checked for. (2)

**Comment by bluciam** [comment]
Working on (3) but having trouble with the interaction between argsparse and unittest. Working on a solution based on: http://stackoverflow.com/questions/15691762/python-after-raising-argparse-argumenterror-argparse-raises-generic-error

**Comment by bluciam** [comment]
Abandoned mocks because it feels like a waste of time, it does not really test what I want. For the moment just catching when argparse should return an exit code. For our current purpose, this is enough.
