### ISSUE TITLE
Testing infrastructure for zebraFont.py: functionality

### ISSUE THREAD

**Issue by bluciam** [plaice/Zebrackets#8]
1.  Check that the font family name is a valid Computer Modern font family. (✅)
- Add a directory with the Computer Modern fonts. (✅)
- Create unit tests for testing proper creation of new fonts.
- Create unit tests to ensure that existing fonts are properly cached.

**Comment by bluciam** [comment]
- Valid Computer Modern font families are enumerated, and checked for. (2) --by @plaice

**Comment by bluciam** [comment]
- The Computer Modern fonts are added (2). --by @plaice

**Comment by plaice** [comment]
The interface is done. Further testing when things go wrong needs to be done.
